link_masses:
- [1,1]

link_inertia:   # point masses at com frame supposed to be a 3*3 matrix
- [0,0]

link_lengths:
- [1,1]

Pos_COM:    #location of point massses wrt to joint frame of corresponding link
- [1,1]

P_l:     #location of joint frame wrt to previos joint frame along x axis
- [0,1,1,0]    #0-1, 1-2,2-3,3-EE

joint_velocity:
- [0.25,0.5]

joint_acc:
- [1,1]

g:
- [0,9.8,0]

theta:
- [0,0]